### ISSUE TITLE
Example on the github page is maybe wrong? 

### ISSUE THREAD

**Issue by ElpadoCan** [kevinjohncutler/ncolor#1]
Awesome package man! I was reading omnipose documentation and found this package and it's fantastic! 

A small note, I think the example on the github homepage is wrong. I get the following error if I try it:

```` 
import ncolor.ncolor as ncolor
ModuleNotFoundError: No module named 'ncolor.ncolor'
````

I changed it to simply `import ncolor` and it works perfectly.

**Comment by kevinjohncutler** [comment]
Thanks for that catch! Got me to update more of the docs haha.
